<a href="https://colab.research.google.com/github/xxcramseyxx/ANN/blob/main/artificial_neural_network_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

# New Section

### Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
df = pd.read_excel('/content/Folds5x2_pp.xlsx')
X = df.iloc[:, : -1].values
y = df.iloc[:, -1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 38520.5117
Epoch 2/100
240/240 [==============================] - 0s 947us/step - loss: 220.1058
Epoch 3/100
240/240 [==============================] - 0s 938us/step - loss: 210.3973
Epoch 4/100
240/240 [==============================] - 0s 889us/step - loss: 199.6747
Epoch 5/100
240/240 [==============================] - 0s 987us/step - loss: 186.6076
Epoch 6/100
240/240 [==============================] - 0s 967us/step - loss: 171.9877
Epoch 7/100
240/240 [==============================] - 0s 921us/step - loss: 156.4742
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 141.2468
Epoch 9/100
240/240 [==============================] - 0s 972us/step - loss: 125.2004
Epoch 10/100
240/240 [==============================] - 0s 961us/step - loss: 109.6478
Epoch 11/100
240/240 [==============================] - 0s 936us/step - loss: 95.2896
Epoch 12/100
240/240 [==============================] -

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[430.17 431.23]
 [461.24 460.01]
 [464.76 461.14]
 ...
 [471.92 473.26]
 [438.94 438.  ]
 [458.05 463.28]]
